### ISSUE TITLE
Error while running utensor-mnist-demo on Mbed Simulator

### ISSUE THREAD

**Issue by Selenatabbara** [uTensor/utensor-mnist-demo#20]
@janjongboom Hello,  I am trying to use the utensor-mnist-demo project and Mbed Simulator (from https://labs.mbed.com/).
I have cloned and run the project on the Mbed Simulator, but I had encountered the following runtime error when the program runs `get_deep_mlp_ctx(ctx, smallImage.get_data()); `in the main :
```
Uncaught RuntimeError: float unrepresentable in integer range
   at emterpret (wasm-function[66]:3344)
   at emterpret (wasm-function[66]:4977)
   at emterpret (wasm-function[66]:4977)
   at __ZN12RequantizeOp7computeEv (wasm-function[7500]:38)
   at emterpret (wasm-function[66]:5564)
   at emterpret (wasm-function[66]:4977)
   at emterpret (wasm-function[66]:4977)
   at Object.Module.emterpret (http://localhost:7900/out/utensor-mnist-demo.js:7442:37)
   at resume (http://localhost:7900/out/utensor-mnist-demo.js:6401:34)
   at http://localhost:7900/out/utensor-mnist-demo.js:6455:11
```

**Comment by janjongboom** [comment]
@Selenatabbara Which branch are you running on? The `develop` branch in this repo does not build for me at all.

/cc @neil-tan

**Comment by Selenatabbara** [comment]
I have used the develop branch but I have deleted the example folder in the uTensor folder.
