### ISSUE TITLE
transform to cpp file error

### ISSUE THREAD

**Issue by Knight-X** [uTensor/utensor-mnist-demo#7]
utensor-cli --output-nodes=OutputLayer/y_pred tensorflow-models/mnist_model/deep_mlp.pb
Traceback (most recent call last):
  File "/usr/local/bin/utensor-cli", line 11, in <module>
    load_entry_point('utensor-cgen==0.0.2', 'console_scripts', 'utensor-cli')()
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/__main__.py", line 81, in cli
    main(**args)
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/__main__.py", line 33, in main
    from .code_generator import CodeGenerator
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/code_generator.py", line 9, in <module>
    from .transformer import NamescopeTransformer
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/transformer/__init__.py", line 2, in <module>
    from ._transform_impl import *
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/transformer/_transform_impl.py", line 7, in <module>
    from ..parser import OperationInfo, TensorInfo
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/parser/__init__.py", line 1, in <module>
    from .pbparser import *
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/parser/pbparser.py", line 11, in <module>
    from ._pbparser_impl import _parse_graph_def
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/parser/_pbparser_impl.py", line 8, in <module>
    from utensor_cgen.parser.types import OperationInfo, TensorInfo
  File "/usr/local/lib/python3.6/site-packages/utensor_cgen-0.0.2-py3.6.egg/utensor_cgen/parser/types.py", line 3, in <module>
    from attr import validators
ImportError: cannot import name 'validators'

utensor_cgen branch - develop
utensor-mnist-demo - master
reinstall by python3 setup.py install

**Comment by mbartling** [comment]
@Knight-X Do you have this same issue on cgen master? If not we should move this bug into cgen

**Comment by dboyliao** [comment]
@Knight-X It looks like you installed my experimental branch `utensor_cgen` codes.
`attr` is a python package I'm trying to use defining IR for the code generator.
Please make sure you install the correct branch which in your case should be `develop`.
